/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import apolloSandbox from "@creazy231/strapi-plugin-apollo-sandbox/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import sentry from "@strapi/plugin-sentry/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import enrollments from "../../src/plugins/enrollments/strapi-admin";
import listTags from "../../src/plugins/list-tags/strapi-admin";
import languageTranslations from "../../src/plugins/language-translations/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    ckeditor: ckeditor,
    "apollo-sandbox": apolloSandbox,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    sentry: sentry,
    seo: seo,
    "users-permissions": usersPermissions,
    enrollments: enrollments,
    "list-tags": listTags,
    "language-translations": languageTranslations,
  },
});
